server:
  context-path: /TVDBEndpoint
  port: 9000
spring:
  profiles:
    active: development
  application:
    name: TVDB
  http:
    encoding:
      charset: UTF-8
      enabled: true
  jta:
    log-base-name: tvdb
flyway:
  schemas:
    - TVDB